-- Bảng hợp đồng của HỆ THỐNG HIỆN TẠI (chưa có pattern): chỉ lưu trạng thái hiện tại.
-- UPDATE ghi đè giá trị cũ, DELETE xóa vĩnh viễn, updated_by / updated_at chỉ cho biết lần sửa cuối.
-- init.sql chạy file này hai lần: vào schema "truoc" (giữ nguyên để so sánh) và "public" (sẽ được migration
-- 001, 002 nâng cấp), nên hai schema xuất phát giống hệt nhau. Tên bảng không ghi schema: theo search_path.
CREATE TABLE contracts (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          text   NOT NULL UNIQUE,                    -- mã hợp đồng, ràng buộc tên contracts_code_key
  customer_name text   NOT NULL,
  product       text   NOT NULL,
  premium       bigint NOT NULL CHECK (premium >= 0),       -- phí bảo hiểm, đồng
  sum_insured   bigint NOT NULL CHECK (sum_insured > 0),    -- số tiền bảo hiểm, đồng
  start_date    date   NOT NULL,
  end_date      date   NOT NULL,
  updated_by    text   NOT NULL DEFAULT 'system',
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Hồ sơ bồi thường tham chiếu hợp đồng. ON DELETE CASCADE (kiểu ORM hay sinh): xóa nhầm hợp đồng là
-- mất luôn hồ sơ bồi thường, đúng triệu chứng ở mục 1 README.
CREATE TABLE claims (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id bigint NOT NULL REFERENCES contracts (id) ON DELETE CASCADE, -- tên claims_contract_id_fkey
  amount      bigint NOT NULL CHECK (amount > 0),
  status      text   NOT NULL DEFAULT 'open',
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX claims_contract_id_idx ON claims (contract_id);
