-- Schema "trước khi áp dụng pattern": khóa ngoại có ràng buộc nhưng KHÔNG có index trên cột tham chiếu
-- (PostgreSQL không tự tạo index cho phía tham chiếu của khóa ngoại).
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE TABLE customers (
  id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  text NOT NULL,
  email text NOT NULL
);

CREATE TABLE orders (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES customers (id),
  status      text NOT NULL,
  total_cents integer NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    integer NOT NULL REFERENCES orders (id),
  product_name text NOT NULL,
  quantity    integer NOT NULL,
  price_cents integer NOT NULL
);

CREATE TABLE shipments (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders (id),
  status   text NOT NULL,
  carrier  text NOT NULL
);
