-- Schema bài 03/02: giá sản phẩm hiện ở ba loại trang (chi tiết, danh mục, deal trang chủ) và được sửa từ ba đường ghi
-- (màn hình admin, job nhập CSV bằng SQL, job khuyến mãi theo lịch). Bản trước và bản sau dùng chung các bảng này;
-- chỉ bản sau ghi vào price_outbox.
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE TABLE products (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category         text NOT NULL,
  name             text NOT NULL,
  list_price       bigint NOT NULL CHECK (list_price > 0), -- giá niêm yết (đồng)
  price            bigint NOT NULL CHECK (price > 0),      -- giá bán hiện hành: niêm yết hoặc khuyến mãi
  price_changed_at timestamptz NOT NULL DEFAULT now()
);
-- Trang danh mục: 20 sản phẩm mỗi trang, theo id.
CREATE INDEX products_category_id_idx ON products (category, id);

-- Khối "deal hôm nay" ở trang chủ: marketing chọn sản phẩm, giá lấy từ products.
CREATE TABLE home_deals (
  position   integer PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products (id)
);

-- Lịch khuyến mãi: job theo lịch đặt giá khuyến mãi lúc starts_at, trả về giá niêm yết lúc ends_at.
CREATE TABLE promotions (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id  integer NOT NULL REFERENCES products (id),
  promo_price bigint NOT NULL CHECK (promo_price > 0),
  starts_at   timestamptz NOT NULL,
  ends_at     timestamptz NOT NULL,
  state       text NOT NULL DEFAULT 'scheduled' CHECK (state IN ('scheduled', 'active', 'ended'))
);
CREATE INDEX promotions_due_start_idx ON promotions (starts_at) WHERE state = 'scheduled';
CREATE INDEX promotions_due_end_idx ON promotions (ends_at) WHERE state = 'active';

-- Bảng nạp của job CSV: đội dữ liệu COPY file vào đây rồi chạy sql/<bản>/import-prices.sql.
CREATE TABLE price_import (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL,
  new_price  bigint NOT NULL CHECK (new_price > 0),
  applied_at timestamptz
);
CREATE INDEX price_import_pending_idx ON price_import (id) WHERE applied_at IS NULL;

-- [PATTERN] Outbox: mỗi lần đổi giá ghi một dòng trong CÙNG transaction với lần đổi; worker đọc dòng đã commit
-- rồi xóa mọi key trang chứa sản phẩm. keys_targeted: số key worker đã gửi lệnh xóa cho sản phẩm đó.
CREATE TABLE price_outbox (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id    integer NOT NULL,
  source        text NOT NULL CHECK (source IN ('admin', 'csv', 'promo')),
  created_at    timestamptz NOT NULL DEFAULT clock_timestamp(),
  processed_at  timestamptz,
  keys_targeted integer
);
CREATE INDEX price_outbox_pending_idx ON price_outbox (id) WHERE processed_at IS NULL;

-- Đơn hàng: charged_price là giá đã tính cho khách; db_price là giá trong DB đúng lúc tạo đơn, chỉ để đếm đơn sai giá.
CREATE TABLE orders (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  variant       text NOT NULL,
  product_id    integer NOT NULL REFERENCES products (id),
  charged_price bigint NOT NULL,
  db_price      bigint NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT clock_timestamp()
);
