-- Schema ví điện tử cho lab Connection Pooling. Chạy một lần khi volume mới (docker-entrypoint-initdb.d).
-- Ứng dụng và PgBouncer dùng role wallet_app KHÔNG phải superuser: role này chỉ dùng được
-- max_connections - superuser_reserved_connections = 100 - 3 = 97 kết nối. Ba chỗ còn lại để superuser
-- (postgres) quản trị và đo pg_stat_activity ngay cả khi ứng dụng đã làm DB đầy.
CREATE ROLE wallet_app LOGIN PASSWORD 'wallet_app';

CREATE TABLE wallets (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_name  text   NOT NULL,
  balance     bigint NOT NULL CHECK (balance >= 0), -- đơn vị: đồng
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Sổ chuyển tiền. created_by lấy từ biến phiên app.user_id (cách hay gặp khi trigger audit hoặc RLS cần biết
-- "ai đang thao tác"). Biến này phải đặt bằng SET LOCAL / set_config(..., true): đặt bằng SET thường thì qua
-- PgBouncer chế độ transaction giá trị rò sang request của người khác (test set-local-does-not-leak).
-- CHECK <> '': request quên đặt biến thì lỗi ngay, không lặng lẽ ghi chuỗi rỗng.
CREATE TABLE transfers (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  from_wallet_id bigint NOT NULL REFERENCES wallets (id),
  to_wallet_id   bigint NOT NULL REFERENCES wallets (id),
  amount         bigint NOT NULL CHECK (amount > 0),
  created_by     text   NOT NULL DEFAULT current_setting('app.user_id') CHECK (created_by <> ''),
  created_at     timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE ON wallets, transfers TO wallet_app;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO wallet_app;
