-- Schema trang sản phẩm: một trang = 5 bảng (sản phẩm, biến thể, giá, ảnh, điểm đánh giá của shop).
-- Index đã đủ cho truy vấn theo id (mục 1: "câu truy vấn đã có index đầy đủ"); cache không thay cho việc này.
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE TABLE shop_ratings (
  shop_id      integer PRIMARY KEY,
  rating_avg   numeric(3, 2) NOT NULL,
  rating_count integer NOT NULL
);

CREATE TABLE products (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id     integer NOT NULL REFERENCES shop_ratings (shop_id),
  name        text NOT NULL,
  description text NOT NULL,
  category    text NOT NULL,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE product_variants (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products (id),
  sku        text NOT NULL UNIQUE,
  name       text NOT NULL,
  stock      integer NOT NULL
);
CREATE INDEX product_variants_product_id_idx ON product_variants (product_id);

CREATE TABLE variant_prices (
  variant_id integer PRIMARY KEY REFERENCES product_variants (id),
  price      bigint NOT NULL CHECK (price > 0),
  list_price bigint NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE product_images (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products (id),
  url        text NOT NULL,
  position   smallint NOT NULL
);
CREATE INDEX product_images_product_id_position_idx ON product_images (product_id, position);
