-- Schema "trước khi áp dụng pattern": vận đơn KHÔNG có cột version, lệnh lưu ghi lại toàn bộ trường của form.
-- Cột version được thêm sau bằng migration db/add-version-column.sql (pnpm db:migrate), như ở hệ thống thật.
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE TABLE shipments (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tracking_code  text NOT NULL UNIQUE,
  recipient_name text NOT NULL,
  address        text NOT NULL,
  appointment_at timestamptz NOT NULL,
  cod_cents      integer NOT NULL,
  note           text NOT NULL DEFAULT '',
  updated_by     text NOT NULL DEFAULT 'system',
  updated_at     timestamptz NOT NULL DEFAULT now()
);
