-- Schema "trước khi áp dụng pattern". Không ghi tên schema để test nạp được vào schema riêng (search_path).
CREATE TABLE IF NOT EXISTS transactions (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id integer NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT clock_timestamp(),
  amount      bigint NOT NULL,
  kind        text NOT NULL,
  description text NOT NULL
);

-- Chỉ có index cho cột lọc (như index khóa ngoại ở bài 02/01); chưa có index theo thứ tự hiển thị.
CREATE INDEX IF NOT EXISTS transactions_merchant_id_idx ON transactions (merchant_id);
